version: '3.7'
services:
  minio:
    container_name: minio-container
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio-persistence:/data
      - ./data/minio-persistence/certs:/certs

    environment:
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
    command: server /data --console-address ":9001"

  db:
    image: "postgres:13.1-alpine"
    container_name: postgresql-container
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=recipes
    depends_on:
      - minio

    volumes:
      - db_volume:/var/lib/postgresql/data/

  recipes-service:
    image: 09031261399/recipes-app:1.0.0
    container_name: app
    depends_on:
      - db

    ports:
      - "8080:8080"
    environment:
      MINIO_URL: http://minio:9000
      MINIO_BUCKET: "recipes"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/recipes
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456


volumes:
  db_volume:
